config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'events',         to: 'pages#events',    as: :events
mount StripeEvent::Engine, at: '/stripe-webhooks'

resources :products, only: [:index, :show]
resources :carts, only: [:index, :show]

resources :orders, only: [:show, :create, :index] do
  resources :payments, only: :new
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  monetize :amount_cents
end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :orders


  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  after_create :send_welcome_email


  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
    # Its important that the location is NOT stored if:
    # - The request method is not GET (non idempotent)
    # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
    #    infinite redirect loop.
    # - The request is an Ajax request as this can lead to very unexpected behaviour.
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
    end

    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
    end


    def after_sign_in_path_for(resource)
      stored_location_for(resource) || root_path
    end


    def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:address])
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    Stripe.api_key = Figaro.env.stripe_api_key
    product = Product.find(params[:product_id])
    order  = Order.create!(product: product, product_sku: product.sku, amount: product.price, state: 'pending', user: current_user)
    session = Stripe::Checkout::Session.create(


      payment_method_types: ['card'],
      line_items: [{
        name: product.sku,
        images: [product.photo_url],
        amount: product.price_cents,
        currency: 'eur',
        quantity: 1
      }],
      success_url: order_url(order),
      cancel_url: order_url(order)
      )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)

  end


  def show
    @order = current_user.orders.find(params[:id])
  end

  def index
    @orders = current_user.orders.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :products, :events]

  def home
  end

  def events
  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    skip_before_action :authenticate_user!, only: [:home, :index, :show]

  def index
    @products = Product.all
  end


  def show
    @product = Product.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="//db.onlinewebfonts.com/c/9fd821abcaa52efaf6db79eec0d6add7?family=BodoniURW" rel="stylesheet" type="text/css"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Toys&Boxes</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/orders/index.html.erb
    <div><%= current_user.orders %></div>
    <%= @orders %>

app/views/orders/show.html.erb
<h1>Thank you for your order</h1>
<div class="product-screen-container">
  <div class="product-screen-left-container">
    <div class="product-photo">
      <%= image_tag @order.product.photo_url, width: '100%' %>
    </div>
  </div>
  <div class="product-screen-right-container">

    <h2>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state%></span></small></h2>
    <ul class="list-unstyled">
      <li><strong>ISSUED ON</strong> <%= @order.created_at.to_date %></li>
      <li><strong>PRODUCT</strong> <%= @order.product.name %> [<%= @order.product_sku %>]</li>
      <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @order.amount %></li>
    </li>
  </ul>
  <p>Estimated delivery in <strong>5 business days</strong> to <%=current_user.address %></p>

</div>
</div>
</div>

app/views/pages/events.erb
<%= content_for(:navbar_class, "navbar-event") %>


<div class="event-banner">
  <div class="banner-content text-center">


    <p><br><br><br></p>
    <p>In order to make our range of products better known, we organize tupperware parties at home. Interrested?
    Contact us.<a style = "color: white" href="tel:+32 470 07 80 80"><div></div><p>+32 470 07 80 80</p></a>
      <a style = "color: white" href="mailto:toysandboxes@gmail.com"><div></div><p>toysandboxes@gmail.com</p></a>
    </p>

<p>
<br><br><br><br><br><br>
</p>
  </div>

</div>

app/views/pages/home.html.erb
<!-- app/views/pages/home.html.erb
So much more than a toy shop.
We can teach other toyshops a thing or two.
Curiosity has a new level
We bring the toy store to you!
For the toys you've always wanted.
Delivering to your imagination.
It's a great day to play!
Delivering play, every day!
C'mon. Let's play!
Make all their wishes come true!
Passion with discretion-->
<%= content_for(:navbar_class, "navbar-home") %>

<div class="banner">
  <div class="banner-content text-center">
    <h1>Toys and Boxes</h1>
    <p>So much more than a toy shop.</p>




    <div class= "container-button-our-products">
      <%= link_to products_path do %>

      <div class="svg-wrapper">
        <svg height="60" width="320" xmlns="http://www.w3.org/2000/svg">
          <rect class="shape" height="60" width="320" />
        </svg>
        <div class="text">Our products</div>
      </div>

      <% end %>
    </div>


  </div>
</div>

app/views/pages/products.html.erb
<h1>Toys & Boxes</h1>

<%= render 'shared/card' %>

app/views/payments/new.html.erb
<h1>Checkout summary</h1>
  <div class="product-screen-container">
    <div class="product-screen-left-container">
      <div class="product-photo"><%= image_tag @order.product.photo_url, width: '100%' %></div>
    </div>
    <div class="product-screen-right-container">

      <p>Purchase of <strong><%= @order.product.name %></strong> for <strong><%= humanized_money_with_symbol @order.amount %></strong></p>
      <div class="col">
        <button id="pay" class="card-category-button-show">Pay</button>
        <script src="https://js.stripe.com/v3"></script>
        <script>
          const paymentButton = document.getElementById('pay');
          paymentButton.addEventListener('click', () => {

            const stripe = Stripe("<%=Figaro.env.stripe_publishable_key%>");
            stripe.redirectToCheckout({
              sessionId: '<%= @order.checkout_session_id %>'
            });
          });
        </script>
      </div>
    </div>
  </div>

app/views/products/index.html.erb
        <h1>Toys & Boxes</h1>



        <%= render 'shared/card' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<div class="product-screen-container">
  <div class="product-screen-left-container">

    <%= render 'shared/gallery-viewer' %>

  </div>
  <div class="product-screen-right-container">
    <p style="font-weight: bold;">Description</p>
    <div><%= @product.description %></div>
    <p style="font-weight: bold;">Price</p>
    <div>€<%= @product.price %></div>

    <% if !@product.sold_out? %>

    <div class="buttons-call-to-actions">
      <div ><%= form_tag orders_path do %>
        <%= hidden_field_tag 'product_id', @product.id %>
        <%= submit_tag 'Buy now', class: 'card-category-button-show' %>
        <% end %>
      </div>
      <div ><%= form_tag orders_path do %>
        <%= hidden_field_tag 'product_id', @product.id %>
        <%= submit_tag 'Add to cart', class: 'card-category-button-show hidden' %>
        <% end %>
      </div>
    </div>

    <% else %>

    <div class="buttons-call-to-actions">
      <div >
        <%= hidden_field_tag 'product_id', @product.id %>
        <%= submit_tag 'Sold out', class: 'button-sold-out' %>
      </div>
      <div ><%= form_tag orders_path do %>
        <%= hidden_field_tag 'product_id', @product.id %>
        <%= submit_tag 'Notify me', class: 'card-category-button-show' %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/shared/_card.html.erb
<div class="cards">

  <% @products.each do |product| %>

  <%= link_to product_path(product) do %>

  <div class="card-super-container">
    <div class="card-container">
      <div class="card-category-price">
       <%= humanized_money_with_symbol(product.price) %>
     </div>
     <div class="card-category">
      <% if product.photo_url.nil? %>
       <div class="card-category-background-image" style="background-image: url(<%= asset_path "coming_soon.jpg" %>)">
        toystoystoystoystoys
      </div>
      <% else %>
      <div class="card-category-background-image" style="background-image: url(<%= asset_path product.photo_url %>)">
        toystoystoystoystoys
      </div>
      <% end %>
    </div>
  </div>
  <div class="card-category-button" >
    ⟶  SHOP
  </div>
</div>

<% end %>
<% end %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_gallery-viewer.html.erb
    <div class="css-gallery">
   <% if !@product.photo_url.nil? & !@product.photo_url_one.nil? & !@product.photo_url_two.nil? & !@product.photo_url_three.nil? %>
      <!-- Main/large images -->
      <div class="viewer" style="background-image: url(<%= asset_path @product.photo_url %>);background-size: cover;">
        <div id="img1" class="img-large">
          <div style="background-image: url(<%= asset_path @product.photo_url %>);"></div>
        </div>
        <div id="img2" class="img-large">
          <div style="background-image: url(<%= asset_path @product.photo_url_one %>);"></div>
        </div>
        <div id="img3" class="img-large">
          <div style="background-image: url(<%= asset_path @product.photo_url_two %>);"></div>
        </div>
        <div id="img4" class="img-large">
          <div style="background-image: url(<%= asset_path @product.photo_url_three %>);"></div>
        </div>
      </div>

      <!-- Thumbnails -->
      <div>
        <ul>
          <li><a href="#img1"><img src=<%= asset_path @product.photo_url %> /></a></li>
          <li><a href="#img2"><img src=<%= asset_path @product.photo_url_one %> /></a></li>
          <li><a href="#img3"><img src=<%= asset_path @product.photo_url_two %> /></a></li>
          <li><a href="#img4"><img src=<%= asset_path @product.photo_url_three %> /></a></li>
        </ul>
      </div>
      <% else %>


      <div class="viewer" style="background-image: url(<%= asset_path "coming_soon.jpg" %>);background-size: cover;">
        <div id="img1" class="img-large">
          <div style="background-image: url(<%= asset_path "coming_soon.jpg" %>);"></div>
        </div>
        <div id="img2" class="img-large">
          <div style="background-image: url(<%= asset_path "coming_soon.jpg" %>);"></div>
        </div>
        <div id="img3" class="img-large">
          <div style="background-image: url(<%= asset_path "coming_soon.jpg" %>);"></div>
        </div>
        <div id="img4" class="img-large">
          <div style="background-image: url(<%= asset_path "coming_soon.jpg" %>);"></div>
        </div>
      </div>

      <!-- Thumbnails -->
      <div>
        <ul>
          <li><a href="#img1"><img src=<%= asset_path "coming_soon.jpg" %> /></a></li>
          <li><a href="#img2"><img src=<%= asset_path "coming_soon.jpg" %> /></a></li>
          <li><a href="#img3"><img src=<%= asset_path "coming_soon.jpg" %> /></a></li>
          <li><a href="#img4"><img src=<%= asset_path "coming_soon.jpg" %> /></a></li>
        </ul>
      </div>


      <% end%>
    </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%=yield(:navbar_class) %>" >
  <%= link_to root_path, class: "navbar-brand " do %>
  <%= image_tag "tb_icon_simple.png"%>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link home" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Boxes", products_path, class: "nav-link " %>
      </li>
      <li class="nav-item active">
        <%= link_to "Events", events_path, class: "nav-link event" %>
      </li>

      <li class="nav-item dropdown active user_icon_empty">
        <%= image_tag "user-simple-s.svg", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My orders", "#", class: "dropdown-item" %>
          <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
<!--
      <li class="nav-item active">
        <%= link_to root_path, class: "navbar-brand " do %>
        <%= image_tag "cart-simple.svg"%>
        <% end %>
      </li>
-->
      <% else %>
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link home" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Boxes", products_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Events", events_path, class: "nav-link event" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
<!--
      <li class="nav-item active">
        <%= link_to root_path, class: "navbar-brand " do %>
        <%= image_tag "cart-simple.svg"%>
        <% end %>
      </li>
-->
      <% end %>
    </ul>
  </div>
</div>